// Code generated by protoc-gen-go. DO NOT EDIT.
// source: snoopd.proto

// protoc --go_out=plugins=grpc:. *.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Nothing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nothing) Reset()         { *m = Nothing{} }
func (m *Nothing) String() string { return proto.CompactTextString(m) }
func (*Nothing) ProtoMessage()    {}
func (*Nothing) Descriptor() ([]byte, []int) {
	return fileDescriptor_a388821cc09ae691, []int{0}
}

func (m *Nothing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nothing.Unmarshal(m, b)
}
func (m *Nothing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nothing.Marshal(b, m, deterministic)
}
func (m *Nothing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nothing.Merge(m, src)
}
func (m *Nothing) XXX_Size() int {
	return xxx_messageInfo_Nothing.Size(m)
}
func (m *Nothing) XXX_DiscardUnknown() {
	xxx_messageInfo_Nothing.DiscardUnknown(m)
}

var xxx_messageInfo_Nothing proto.InternalMessageInfo

type History struct {
	RoundTrips           []string `protobuf:"bytes,1,rep,name=RoundTrips,proto3" json:"RoundTrips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *History) Reset()         { *m = History{} }
func (m *History) String() string { return proto.CompactTextString(m) }
func (*History) ProtoMessage()    {}
func (*History) Descriptor() ([]byte, []int) {
	return fileDescriptor_a388821cc09ae691, []int{1}
}

func (m *History) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_History.Unmarshal(m, b)
}
func (m *History) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_History.Marshal(b, m, deterministic)
}
func (m *History) XXX_Merge(src proto.Message) {
	xxx_messageInfo_History.Merge(m, src)
}
func (m *History) XXX_Size() int {
	return xxx_messageInfo_History.Size(m)
}
func (m *History) XXX_DiscardUnknown() {
	xxx_messageInfo_History.DiscardUnknown(m)
}

var xxx_messageInfo_History proto.InternalMessageInfo

func (m *History) GetRoundTrips() []string {
	if m != nil {
		return m.RoundTrips
	}
	return nil
}

type ReqID struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqID) Reset()         { *m = ReqID{} }
func (m *ReqID) String() string { return proto.CompactTextString(m) }
func (*ReqID) ProtoMessage()    {}
func (*ReqID) Descriptor() ([]byte, []int) {
	return fileDescriptor_a388821cc09ae691, []int{2}
}

func (m *ReqID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqID.Unmarshal(m, b)
}
func (m *ReqID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqID.Marshal(b, m, deterministic)
}
func (m *ReqID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqID.Merge(m, src)
}
func (m *ReqID) XXX_Size() int {
	return xxx_messageInfo_ReqID.Size(m)
}
func (m *ReqID) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqID.DiscardUnknown(m)
}

var xxx_messageInfo_ReqID proto.InternalMessageInfo

func (m *ReqID) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type Response struct {
	Response             string   `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a388821cc09ae691, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*Nothing)(nil), "protobuf.Nothing")
	proto.RegisterType((*History)(nil), "protobuf.History")
	proto.RegisterType((*ReqID)(nil), "protobuf.ReqID")
	proto.RegisterType((*Response)(nil), "protobuf.Response")
}

func init() { proto.RegisterFile("snoopd.proto", fileDescriptor_a388821cc09ae691) }

var fileDescriptor_a388821cc09ae691 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xce, 0xcb, 0xcf,
	0x2f, 0x48, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a,
	0x9c, 0x5c, 0xec, 0x7e, 0xf9, 0x25, 0x19, 0x99, 0x79, 0xe9, 0x4a, 0x9a, 0x5c, 0xec, 0x1e, 0x99,
	0xc5, 0x25, 0xf9, 0x45, 0x95, 0x42, 0x72, 0x5c, 0x5c, 0x41, 0xf9, 0xa5, 0x79, 0x29, 0x21, 0x45,
	0x99, 0x05, 0xc5, 0x12, 0x8c, 0x0a, 0xcc, 0x1a, 0x9c, 0x41, 0x48, 0x22, 0x4a, 0xe2, 0x5c, 0xac,
	0x41, 0xa9, 0x85, 0x9e, 0x2e, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x2e, 0x12, 0x8c, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x4c, 0x9e, 0x2e, 0x4a, 0x6a, 0x5c, 0x1c, 0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5,
	0xa9, 0x42, 0x52, 0x08, 0x36, 0x54, 0x05, 0x9c, 0x6f, 0x54, 0xc4, 0xc5, 0x19, 0x0c, 0x76, 0x90,
	0x63, 0x80, 0xa7, 0x90, 0x09, 0x17, 0x97, 0x7b, 0x6a, 0x09, 0xcc, 0x6e, 0x41, 0x3d, 0x98, 0xe3,
	0xf4, 0xa0, 0x2e, 0x93, 0x42, 0x12, 0x82, 0xaa, 0x52, 0x62, 0x10, 0xd2, 0xe7, 0x62, 0x0b, 0x4a,
	0x2d, 0x4e, 0xcd, 0x4b, 0x11, 0xe2, 0x47, 0x48, 0x83, 0x5d, 0x25, 0x25, 0x84, 0x2c, 0x00, 0xb1,
	0x51, 0x89, 0x21, 0x89, 0x0d, 0x2c, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xe8, 0x6d,
	0x11, 0x0b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SnoopdAPIClient is the client API for SnoopdAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SnoopdAPIClient interface {
	GetHistory(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*History, error)
	Resend(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*Response, error)
}

type snoopdAPIClient struct {
	cc *grpc.ClientConn
}

func NewSnoopdAPIClient(cc *grpc.ClientConn) SnoopdAPIClient {
	return &snoopdAPIClient{cc}
}

func (c *snoopdAPIClient) GetHistory(ctx context.Context, in *Nothing, opts ...grpc.CallOption) (*History, error) {
	out := new(History)
	err := c.cc.Invoke(ctx, "/protobuf.SnoopdAPI/GetHistory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snoopdAPIClient) Resend(ctx context.Context, in *ReqID, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protobuf.SnoopdAPI/Resend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnoopdAPIServer is the server API for SnoopdAPI service.
type SnoopdAPIServer interface {
	GetHistory(context.Context, *Nothing) (*History, error)
	Resend(context.Context, *ReqID) (*Response, error)
}

// UnimplementedSnoopdAPIServer can be embedded to have forward compatible implementations.
type UnimplementedSnoopdAPIServer struct {
}

func (*UnimplementedSnoopdAPIServer) GetHistory(ctx context.Context, req *Nothing) (*History, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (*UnimplementedSnoopdAPIServer) Resend(ctx context.Context, req *ReqID) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resend not implemented")
}

func RegisterSnoopdAPIServer(s *grpc.Server, srv SnoopdAPIServer) {
	s.RegisterService(&_SnoopdAPI_serviceDesc, srv)
}

func _SnoopdAPI_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nothing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnoopdAPIServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SnoopdAPI/GetHistory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnoopdAPIServer).GetHistory(ctx, req.(*Nothing))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnoopdAPI_Resend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnoopdAPIServer).Resend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.SnoopdAPI/Resend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnoopdAPIServer).Resend(ctx, req.(*ReqID))
	}
	return interceptor(ctx, in, info, handler)
}

var _SnoopdAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.SnoopdAPI",
	HandlerType: (*SnoopdAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _SnoopdAPI_GetHistory_Handler,
		},
		{
			MethodName: "Resend",
			Handler:    _SnoopdAPI_Resend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snoopd.proto",
}
