snoopd:
  name: "Snoopd"
  version: "v1.0"
  debug_mode: true
  storing_path: "/tmp/snoopd"
  http_port: 8080
  https_port: 8081
  tls_cert: "/etc/snoopd/snoopd.pem"
  tls_key: "/etc/snoopd/snoopd.key"
  log:
    logger_tag: "snoopd"
    logger_file: "/var/log/snoopd.log"
    response_logger_tag: "snoopd_response"
    response_logger_file: "/var/log/snoopd_access.log"
